### ISSUE TITLE
npm run samples-generator error

### ISSUE THREAD

**Issue by Quynh-Nguyen** [AnalyticalGraphicsInc/3d-tiles-tools#127]
Node version: v4.8.3
Also tried with: v6.10.3
> $ node bin/3d-tiles-samples-generator.js 
Unhandled rejection TypeError: Cannot read property 'webgl2' of undefined
    at combineShader (/var/www/html/3d/3d-tiles-tools/samples-generator/node_modules/cesium/Source/Renderer/ShaderSource.js:247:20)
    at ShaderSource.createCombinedVertexShader (/var/www/html/3d/3d-tiles-tools/samples-generator/node_modules/cesium/Source/Renderer/ShaderSource.js:334:16)
    at patchProgram (/var/www/html/3d/3d-tiles-tools/samples-generator/node_modules/gltf-pipeline/lib/octEncodeNormals.js:169:21)
    at /var/www/html/3d/3d-tiles-tools/samples-generator/node_modules/gltf-pipeline/lib/octEncodeNormals.js:94:21
    at /var/www/html/3d/3d-tiles-tools/samples-generator/node_modules/gltf-pipeline/lib/getAccessorsForSemantic.js:31:33
    at Promise._execute (/var/www/html/3d/3d-tiles-tools/samples-generator/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/var/www/html/3d/3d-tiles-tools/samples-generator/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/var/www/html/3d/3d-tiles-tools/samples-generator/node_modules/bluebird/js/release/promise.js:79:10)
    at getAccessorsForSemantic (/var/www/html/3d/3d-tiles-tools/samples-generator/node_modules/gltf-pipeline/lib/getAccessorsForSemantic.js:18:12)
    at /var/www/html/3d/3d-tiles-tools/samples-generator/node_modules/gltf-pipeline/lib/octEncodeNormals.js:46:9
    at Promise._execute (/var/www/html/3d/3d-tiles-tools/samples-generator/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/var/www/html/3d/3d-tiles-tools/samples-generator/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/var/www/html/3d/3d-tiles-tools/samples-generator/node_modules/bluebird/js/release/promise.js:79:10)
    at octEncodeNormals (/var/www/html/3d/3d-tiles-tools/samples-generator/node_modules/gltf-pipeline/lib/octEncodeNormals.js:36:12)
    at Function.Pipeline.processJSONWithExtras (/var/www/html/3d/3d-tiles-tools/samples-generator/node_modules/gltf-pipeline/lib/Pipeline.js:116:28)
    at /var/www/html/3d/3d-tiles-tools/samples-generator/node_modules/gltf-pipeline/lib/Pipeline.js:60:29

**Comment by lilleyse** [comment]
Thanks for reporting, there was an inconsistency in versions for the third party libraries. Should be fixed once https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/pull/128 is merged.

**Comment by Quynh-Nguyen** [comment]
@lilleyse 
Hi lilleyse,
I'm trying to export my fbx 3D objects to 3D tiles cesium but when I'm converted to b3dm file and tileset.json by FME tools.
I got problems about coordinate wrong and altitude wrong.
![image](https://user-images.githubusercontent.com/15666964/31113478-b237330e-a843-11e7-8a67-d594aaff67b4.png)
Can you please help me how I can convert to b3dm files from FBX files with this sample-generator?
I can't find where is input object at 3d-tiles-samples-generator.js tools.

**Comment by lilleyse** [comment]
The samples-generator project doesn't do any conversions, instead it is meant as a reference and is used for generating the sample tilesets in Cesium and https://github.com/AnalyticalGraphicsInc/3d-tiles-samples.

Can you post this question to the [Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev) instead? We use github primarily for bugs and feature requests. Feel free to attach the FBX files and tileset to the forum message, it will be easier to debug that way. Thanks!
